### ISSUE TITLE
Get the updated list onto HAR website

### ISSUE THREAD

**Issue by montanaflynn** [ahmadnassri/har-resources#1]
The [official HAR website](http://www.softwareishard.com/blog/har-12-spec/) has it's own [list of tools](http://www.softwareishard.com/blog/har-adopters/) so I wonder if @janodvarko would be interested in updating his website to include the other tools that are listed in this repo.

**Comment by ahmadnassri** [comment]
I was thinking the reverse, keeping the list as a repo, allows community members to easily contribute without waiting on website authors to push updates ...

that's one way, can also easily build git hooks to update web pages once the repo is updated... which is something I was thinking about last night ... can build a quick github.io page that's automatically generated from the repo's content.

**Comment by montanaflynn** [comment]
I was only suggesting @janodvarko include tools in this repo that are not on his website. If and how he goes about that would be up to him.

**Comment by janodvarko** [comment]
I could sync up  my site with the repo at some point I guess...
Honza

**Comment by nijikokun** [comment]
It would be easier @janodvarko to link to the repository rather than sync, as a quick and simple solution.

**Comment by ahmadnassri** [comment]
i'm thinking of splitting into jekyll collection format (individual file per app/project) 
1. makes it easier to parse
2. can generate simple jekyll site out of it too

**Comment by ahmadnassri** [comment]
@janodvarko with recent update, i've turned the items into [jekyll collections](http://jekyllrb.com/docs/collections/) which makes it easier to iterate / parse the files in the folders to generate output (if you're not using jekyll already ...)

I'm now auto-generating the web view of the list using github + jekyll: http://ahmadnassri.github.io/har-resources/

**Comment by janodvarko** [comment]
Yep, I might just link to this repo as a quick workaround, but what @ahmadnassri did looks great!

Honza
